WARNING 2021-12-06 22:27:57,199 log 831853 140572618626816 Not Found: /robots.txt
WARNING 2021-12-06 22:27:57,200 basehttp 831853 140572618626816 "GET /robots.txt HTTP/1.1" 404 2179
WARNING 2021-12-07 05:57:58,747 log 831853 140572643804928 Forbidden (Permission denied): /admin/form_produksi/productionform/
Traceback (most recent call last):
  File "/home/Vieri/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/Vieri/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/Vieri/.local/lib/python3.6/site-packages/django/contrib/admin/options.py", line 614, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/Vieri/.local/lib/python3.6/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/Vieri/.local/lib/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/Vieri/.local/lib/python3.6/site-packages/django/contrib/admin/sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "/home/Vieri/.local/lib/python3.6/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/Vieri/.local/lib/python3.6/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/Vieri/.local/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1690, in changelist_view
    raise PermissionDenied
django.core.exceptions.PermissionDenied
WARNING 2021-12-07 05:57:58,749 basehttp 831853 140572643804928 "GET /admin/form_produksi/productionform/ HTTP/1.1" 403 135
WARNING 2021-12-07 05:58:37,484 log 831853 140572643804928 Forbidden (Permission denied): /admin/form_produksi/productionform/21598/change/
Traceback (most recent call last):
  File "/home/Vieri/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/Vieri/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/Vieri/.local/lib/python3.6/site-packages/django/contrib/admin/options.py", line 614, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/Vieri/.local/lib/python3.6/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/Vieri/.local/lib/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/Vieri/.local/lib/python3.6/site-packages/django/contrib/admin/sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "/home/Vieri/.local/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1656, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "/home/Vieri/.local/lib/python3.6/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/Vieri/.local/lib/python3.6/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/Vieri/.local/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1534, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/home/Vieri/.local/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1562, in _changeform_view
    raise PermissionDenied
django.core.exceptions.PermissionDenied
WARNING 2021-12-07 05:58:37,485 basehttp 831853 140572643804928 "GET /admin/form_produksi/productionform/21598/change/ HTTP/1.1" 403 135
WARNING 2021-12-07 05:58:47,593 log 831853 140572643804928 Forbidden (Permission denied): /admin/form_produksi/productionform/21598/change/
Traceback (most recent call last):
  File "/home/Vieri/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/Vieri/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/Vieri/.local/lib/python3.6/site-packages/django/contrib/admin/options.py", line 614, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/Vieri/.local/lib/python3.6/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/Vieri/.local/lib/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/Vieri/.local/lib/python3.6/site-packages/django/contrib/admin/sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "/home/Vieri/.local/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1656, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "/home/Vieri/.local/lib/python3.6/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/Vieri/.local/lib/python3.6/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/Vieri/.local/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1534, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/home/Vieri/.local/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1562, in _changeform_view
    raise PermissionDenied
django.core.exceptions.PermissionDenied
WARNING 2021-12-07 05:58:47,594 basehttp 831853 140572643804928 "GET /admin/form_produksi/productionform/21598/change/ HTTP/1.1" 403 135
WARNING 2021-12-07 08:43:32,166 log 831853 140572660590336 Not Found: /admin/form_produksi/reportshiftperkk/add/
WARNING 2021-12-07 08:43:32,166 basehttp 831853 140572660590336 "GET /admin/form_produksi/reportshiftperkk/add/ HTTP/1.1" 404 8738
WARNING 2021-12-07 08:59:01,335 log 831853 140571637171968 Forbidden (Permission denied): /admin/form_produksi/productionform/
Traceback (most recent call last):
  File "/home/Vieri/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/Vieri/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/Vieri/.local/lib/python3.6/site-packages/django/contrib/admin/options.py", line 614, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/Vieri/.local/lib/python3.6/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/Vieri/.local/lib/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/Vieri/.local/lib/python3.6/site-packages/django/contrib/admin/sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "/home/Vieri/.local/lib/python3.6/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/Vieri/.local/lib/python3.6/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/Vieri/.local/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1690, in changelist_view
    raise PermissionDenied
django.core.exceptions.PermissionDenied
WARNING 2021-12-07 08:59:01,336 basehttp 831853 140571637171968 "GET /admin/form_produksi/productionform/ HTTP/1.1" 403 135
WARNING 2021-12-07 08:59:05,565 log 831853 140571637171968 Not Found: /admin/form_produksi/reportshiftperkk/
WARNING 2021-12-07 08:59:05,565 basehttp 831853 140571637171968 "GET /admin/form_produksi/reportshiftperkk/ HTTP/1.1" 404 8726
WARNING 2021-12-07 08:59:08,122 log 831853 140572643804928 Not Found: /admin/form_produksi/reportshiftperkk/
WARNING 2021-12-07 08:59:08,122 basehttp 831853 140572643804928 "GET /admin/form_produksi/reportshiftperkk/ HTTP/1.1" 404 8725
WARNING 2021-12-07 09:03:06,372 log 831853 140572643804928 Forbidden (Permission denied): /admin/form_produksi/productionform/
Traceback (most recent call last):
  File "/home/Vieri/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/Vieri/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/Vieri/.local/lib/python3.6/site-packages/django/contrib/admin/options.py", line 614, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/Vieri/.local/lib/python3.6/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/Vieri/.local/lib/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/Vieri/.local/lib/python3.6/site-packages/django/contrib/admin/sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "/home/Vieri/.local/lib/python3.6/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/Vieri/.local/lib/python3.6/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/Vieri/.local/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1690, in changelist_view
    raise PermissionDenied
django.core.exceptions.PermissionDenied
WARNING 2021-12-07 09:03:06,373 basehttp 831853 140572643804928 "GET /admin/form_produksi/productionform/?machine__id__exact=63&user_group__id__exact=1 HTTP/1.1" 403 135
WARNING 2021-12-07 09:03:53,249 log 831853 140571653957376 Not Found: /admin/form_produksi/reportshiftperkk/add/
WARNING 2021-12-07 09:03:53,249 basehttp 831853 140571653957376 "GET /admin/form_produksi/reportshiftperkk/add/ HTTP/1.1" 404 8738
ERROR 2021-12-07 09:50:07,063 log 831853 140571645564672 Internal Server Error: /admin/masterdata/masterbarang/
Traceback (most recent call last):
  File "/home/Vieri/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/Vieri/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/Vieri/.local/lib/python3.6/site-packages/django/contrib/admin/options.py", line 614, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/Vieri/.local/lib/python3.6/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/Vieri/.local/lib/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/Vieri/.local/lib/python3.6/site-packages/django/contrib/admin/sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "/home/Vieri/.local/lib/python3.6/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/Vieri/.local/lib/python3.6/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/Vieri/.local/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1693, in changelist_view
    cl = self.get_changelist_instance(request)
  File "/home/Vieri/.local/lib/python3.6/site-packages/django/contrib/admin/options.py", line 748, in get_changelist_instance
    sortable_by,
  File "/home/Vieri/.local/lib/python3.6/site-packages/django/contrib/admin/views/main.py", line 99, in __init__
    self.queryset = self.get_queryset(request)
  File "/home/Vieri/.local/lib/python3.6/site-packages/django/contrib/admin/views/main.py", line 483, in get_queryset
    qs, search_use_distinct = self.model_admin.get_search_results(request, qs, self.query)
  File "/home/Vieri/project_dir/oee_impc/masterdata/admin.py", line 258, in get_search_results
    elif 'prefilledform' in url and 'change' in url:
TypeError: argument of type 'NoneType' is not iterable
ERROR 2021-12-07 09:50:07,065 basehttp 831853 140571645564672 "GET /admin/masterdata/masterbarang/ HTTP/1.1" 500 118159
ERROR 2021-12-07 09:50:10,590 log 831853 140571628779264 Internal Server Error: /admin/masterdata/masterbarang/
Traceback (most recent call last):
  File "/home/Vieri/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/Vieri/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/Vieri/.local/lib/python3.6/site-packages/django/contrib/admin/options.py", line 614, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/Vieri/.local/lib/python3.6/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/Vieri/.local/lib/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/Vieri/.local/lib/python3.6/site-packages/django/contrib/admin/sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "/home/Vieri/.local/lib/python3.6/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/Vieri/.local/lib/python3.6/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/Vieri/.local/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1693, in changelist_view
    cl = self.get_changelist_instance(request)
  File "/home/Vieri/.local/lib/python3.6/site-packages/django/contrib/admin/options.py", line 748, in get_changelist_instance
    sortable_by,
  File "/home/Vieri/.local/lib/python3.6/site-packages/django/contrib/admin/views/main.py", line 99, in __init__
    self.queryset = self.get_queryset(request)
  File "/home/Vieri/.local/lib/python3.6/site-packages/django/contrib/admin/views/main.py", line 483, in get_queryset
    qs, search_use_distinct = self.model_admin.get_search_results(request, qs, self.query)
  File "/home/Vieri/project_dir/oee_impc/masterdata/admin.py", line 258, in get_search_results
    elif 'prefilledform' in url and 'change' in url:
TypeError: argument of type 'NoneType' is not iterable
ERROR 2021-12-07 09:50:10,591 basehttp 831853 140571628779264 "GET /admin/masterdata/masterbarang/ HTTP/1.1" 500 118159
ERROR 2021-12-07 14:03:33,502 basehttp 831853 140573031732992 "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 500 59
ERROR 2021-12-07 14:04:51,326 basehttp 831853 140572643804928 "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 500 59
WARNING 2021-12-07 17:26:20,699 basehttp 831853 140571611993856 "  /*à     Cookie: mstshash=Administr" 400 -
